---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4870900593-9QYPS4iQ3P76KnxJGpHn9Zx36eI10pGe7B5xPk3
:access_token_secret: 5ZBxul75lGx5JlxGW8ArLxl3QdYqQeZ2gnjUhdBOhpFUE
